### ISSUE TITLE
IMAP Connection Authentication Failed

### ISSUE THREAD

**Issue by harshitpeer** [barbushin/php-imap#276]
I am using your lib on many servers and its working fine on almost all of them. 
However, recently I came across a weird issue where IMAP_OPEN is working fine but when I use your library its giving me a Authentication Failed error.

Error Log

`[24-Jan-2019 04:12:56 UTC] PHP Fatal error:  Uncaught PhpImap\ConnectionException: IMAP method imap_open() failed with error: Can not authenticate to IMAP server: [AUTHENTICATIONFAILED] Authentication failed. in /home/XXXXX/XXXXX/core/PhpImap/Mailbox.php:862
Stack trace:
#0 /home/XXXXX/XXXXX/core/PhpImap/Mailbox.php(148): PhpImap\Mailbox->imap('open', Array, false, 'PhpImap\\Connect...')
#1 /home/XXXXX/XXXXX/core/PhpImap/Mailbox.php(134): PhpImap\Mailbox->initImapStream()
#2 /home/XXXXX/XXXXX/core/PhpImap/Mailbox.php(112): PhpImap\Mailbox->initImapStreamWithRetry()
#3 /home/XXXXX/XXXXX/core/PhpImap/Mailbox.php(852): PhpImap\Mailbox->getImapStream()
#4 /home/XXXXX/XXXXX/core/PhpImap/Mailbox.php(244): PhpImap\Mailbox->imap('search', Array)
#5 /home/XXXXX/XXXXX/test.php(26): PhpImap\Mailbox->searchMailbox('BEFORE 14-Jan-2...')`

I also tried to test IMAP connection on pingability and its working fine over there as well. Any suggestion?

**Comment by harshitpeer** [comment]
I figured out the issue. It was with the Password.
Because of some special symbol in the password, your lib was changing it.

I think you should you bypass any password field from any conversion as someone else can also face this.

Password was - OKiLsP+WQ&Yh

Just pass this password through your code and see how it changes it.
