### ISSUE TITLE
Uncaught Exception: decodeMimeStr() Can not decode an empty string!

### ISSUE THREAD

**Issue by AdamCZ001** [barbushin/php-imap#439]
` thrown in vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 1193
[22-Jan-2020 14:35:35 Europe/Prague] PHP Fatal error:  Uncaught Exception: decodeMimeStr() Can not decode an empty string! in vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:1193
Stack trace:
#0 vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(911): PhpImap\Mailbox->decodeMimeStr(' ', 'UTF-8')
#1 vendor/php-imap/php-imap/src/PhpImap/Mailbox.php(1008): PhpImap\Mailbox->getMailHeader(38915)
#2 web/funkce.php(2394): PhpImap\Mailbox->getMail(38915)
#3 ajax_adam.php(969): stahnoutNoveEmaily(NULL)
#4 {main}`

**Comment by Sebi94nbg** [comment]
This exception should not appear with the latest version of this library. Please make sure, that you're using the latest version.

**Comment by AdamCZ001** [comment]
Updating php-imap/php-imap (3.0.6 => 3.0.33): Downloading (100%)

**Comment by jsmcm** [comment]
This bug seems to be back in version 4.0.0

**Comment by bapcltd-marv** [comment]
see #502, should be fixed ?

**Comment by LucianoVandi** [comment]
> This bug seems to be back in version 4.0.0

Got the same error with version 4.0.0. Digging deeper I see that **textPlain** and **textHtml** are both null.

```#dataInfo: array:2 [
    0 => array:3 [
      0 => PhpImap\DataPartInfo^ {#800
        +id: 27128
        +encoding: 4
        +charset: "us-ascii"
        +part: 1
        +mail: PhpImap\Mailbox^ {#774}
        +options: 1
        #data: null
      }
      1 => PhpImap\DataPartInfo^ {#803
        +id: 27128
        +encoding: 0
        +charset: "us-ascii"
        +part: 3
        +mail: PhpImap\Mailbox^ {#774}
        +options: 1
        #data: null
      }
      2 => PhpImap\DataPartInfo^ {#806
        +id: 27128
        +encoding: 0
        +charset: "us-ascii"
        +part: 5
        +mail: PhpImap\Mailbox^ {#774}
        +options: 1
        #data: null
      }
    ]
    1 => []
  ]
  -textPlain: null
  -textHtml: null
  +id: 27128
  +isDraft: false
  +date: "2020-06-11T22:06:55+02:00"
```
The mail body is actually present:

``` X-Mailer: iPhone Mail (17A878)

--Apple-Mail-84F83C86-FEBC-4644-8287-10EC89538EAD
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod=
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, =
quis nostrud exercitation ullamco laboris nisi ut aliquip.=20

--Apple-Mail-84F83C86-FEBC-4644-8287-10EC89538EAD
Content-Type: image/jpeg; name=image0.jpeg; x-apple-part-url=182BBF5E-0BD9-4664-B251-A90319C3995E-L0-001
Content-Disposition: inline; filename=image0.jpeg
Content-Transfer-Encoding: base64

--Apple-Mail-84F83C86-FEBC-4644-8287-10EC89538EAD
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

--Apple-Mail-84F83C86-FEBC-4644-8287-10EC89538EAD
Content-Type: image/jpeg; name=image1.jpeg; x-apple-part-url=C4924EFE-5D33-4949-8237-39EEB6C5CCF3-L0-001
Content-Disposition: inline; filename=image1.jpeg
Content-Transfer-Encoding: base64

--Apple-Mail-84F83C86-FEBC-4644-8287-10EC89538EAD
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Inviato da iPhone
--Apple-Mail-84F83C86-FEBC-4644-8287-10EC89538EAD--
```

Should I need to downgrade?

**Comment by bapcltd-marv** [comment]
have you tested with the develop branch?

**Comment by LucianoVandi** [comment]
@bapcltd-marv tested right now. It's not happening with dev branch.

**Comment by LucianoVandi** [comment]
Any plan to merge this fix in 4.x release?

**Comment by bapcltd-marv** [comment]
should be in [4.1.0](https://github.com/barbushin/php-imap/releases/tag/4.1.0) ?
